{
 "title": "hambn's APISIX dashdash",
 "description": "Dashboard for MicroService API Gateway Apache APISIX, made by hambn",
 "tags": [
  "APISIX",
  "prometheus",
  "hamban"
 ],
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(apisix_http_status,service)"
   },
   {
    "name": "route",
    "query": "label_values(apisix_http_status,route)"
   },
   {
    "name": "instance",
    "query": "label_values(apisix_http_status,instance)"
   },
   {
    "name": "consumer",
    "query": "label_values(apisix_http_status,consumer)"
   },
   {
    "name": "instance",
    "query": "label_values(apisix_http_status,instance)"
   },
   {
    "name": "consumer",
    "query": "label_values(apisix_http_status,consumer)"
   },
   {
    "name": "node",
    "query": "label_values(apisix_http_status,node)"
   }
  ]
 },
 "panels": [
  {
   "title": "APISIX Nginx",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(apisix_http_requests_total{instance=~\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Accepted Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(apisix_nginx_http_current_connections{state=\"accepted\", instance=~\"$instance\"})",
       "legendFormat": "Accepted"
      }
     ]
    },
    {
     "title": "Handled Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(apisix_nginx_http_current_connections{state=\"handled\", instance=~\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Nginx connection state",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(apisix_nginx_http_current_connections{state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "APISIX Bandwidth",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(apisix_bandwidth{instance=~\"$instance\"}[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Ingress per service/route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(irate(apisix_bandwidth{type=\"ingress\",service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__interval])) by (route)",
       "legendFormat": "service:{{service}}"
      },
      {
       "expr": "sum(irate(apisix_bandwidth{type=\"ingress\",service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__interval])) by (service)",
       "legendFormat": "route:{{route}}"
      }
     ]
    },
    {
     "title": "Egress per service/route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(irate(apisix_bandwidth{type=\"egress\",service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__interval])) by (route)",
       "legendFormat": "service:{{service}}"
      },
      {
       "expr": "sum(irate(apisix_bandwidth{type=\"egress\",service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__interval])) by (service)",
       "legendFormat": "route:{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "APISIX HTTP",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of successful responses",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", code!~\"5..\"}[$__interval]))\r\n/\r\nsum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[$__interval])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentage of successful responses",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", code!~\"5..\"}[$__interval]))\r\n/\r\nsum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[$__interval])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", code!~\"5..\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", code=~\"2..\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", code=~\"3..\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", code=~\"4..\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", code=~\"5..\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests per second (RPS) by status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\",code!~\"5..\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\",code=~\"2..\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\",code=~\"5..\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\",code=~\"4..\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests per second (RPS) by status code",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\",code=~\"5..\"}[$__interval])) by (code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\",code=~\"4..\"}[$__interval])) by (code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\",code=~\"2..\"}[$__interval])) by (code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\",code=~\"3..\"}[$__interval])) by (code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests per second (RPS) per service/route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__interval])) by (route)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__interval])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "APISIX Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upstream Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "APISIX Misc",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Etcd modify indexes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(apisix_etcd_modify_indexes{instance=~\"$instance\"}) by (key)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Etcd reachable",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(apisix_etcd_reachable{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nginx metric errors",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(apisix_nginx_metric_errors_total{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}